name: Publish Pypi

on:
  push:
    tags:
      - 'v*.*.*' # Run on version tags for publishing

jobs:
  publish-to-pypi:
    if: startsWith(github.ref, 'refs/tags/v') # Run only if the push is a tag starting with 'v'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install twine build
          pip install toml
      - name: Extract Version from Git Tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')" >> $GITHUB_ENV
      - name: Update pyproject.toml
        run: |
          python -c "import toml; \
                     pyproject = toml.load('pyproject.toml'); \
                     pyproject['project']['version'] = '${{ env.VERSION }}'; \
                     toml.dump(pyproject, open('pyproject.toml', 'w'))"
      - name: Build package
        run: |
          python -m build
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: |
          twine upload --repository pypi dist/*